/*
 * The Bonobo Document Model
 *
 * Author: 
 *     Miguel de Icaza (miguel@gnu.org)
 *
 */
#include <gnome-factory.idl>
#include "gnome-object.idl"

#include "base.idl"

#include "storage.idl"
#include "persist.idl"

#include "moniker.idl"

#include "advise.idl"

#include "container.idl"
#include "clientsite.idl"
#include "bobject.idl"
#include "inplace.idl"

