module GNOME {

	interface AdviseSink : GNOME::obj {
		void notify (in long notify_type);
		
		/**
		 * on_rename:
		 * @new_full_name: New name of the server
		 * document.
		 *
		 * Invoked by a server object to notify its
		 * container that now its contents are being
		 * stored in @new_full_name
		 */
		void on_rename (in string new_full_name);

		/**
		 * on_save:
		 *
		 * Notifies that the object has been saved
		 */
	};
};
