/*
 * Bonobo_Config.idl: The Bonobo Configuration System
 *
 * Author:
 *	Dietmar Maurer (dietmar@ximian.com)
 */

#ifndef __BONOBO_CONFIG_IDL__
#define __BONOBO_CONFIG_IDL__

#include <Bonobo_Property.idl>

module Bonobo {
	typedef sequence<string> KeyList;

	/*
	 *  This interface is always aggregated with an
	 * event source that supplies change notification
	 * on properties.
	 */
	interface ConfigDatabase : Unknown {
		
		exception BackendFailed {};
		exception InvalidType {};
		exception NotFound {};

		readonly attribute boolean writeable;

		any          getValue    (in string key, in string locale)
			raises (NotFound, BackendFailed);

		void         setValue    (in string key, in any value)
			raises (BackendFailed);

		any          getDefault  (in string key, in string locale)
			raises (NotFound, BackendFailed);

		KeyList      listDirs    (in string dir)
			raises (BackendFailed);

		KeyList      listKeys    (in string dir)
			raises (BackendFailed);

		boolean      dirExists   (in string dir)
			raises (BackendFailed);
		
		void         removeValue (in string key)
			raises (BackendFailed);

		void         removeDir   (in string dir)
			raises (BackendFailed);

		void         addDatabase (in ConfigDatabase ddb, 
					  in string filter_path,
					  in string append_path)
			raises (BackendFailed);

		void         sync        ()
			raises (BackendFailed);
	};

};

#endif /* ! __BONOBO_CONFIG_IDL__ */
