/* -*- Mode: C; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 8 -*- */
/*
 * Bonobo_GenericFactory.idl: Basic object factory interface, based on CORBA
 * LifeCycle version
 */

#ifndef __BONOBO_GENERIC_FACTORY_IDL__
#define __BONOBO_GENERIC_FACTORY_IDL__

#if !defined(__BONOBO_GENERIC_FACTORY_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs bonobo-activation/Bonobo_GenericFactory.h
%}
#pragma inhibit push
#endif

#include <Bonobo_Unknown.idl>

module Bonobo {
	typedef sequence<string> StringList;
        
	interface GenericFactory : Bonobo::Unknown {
		exception CannotActivate { };

		boolean manufactures (in string obj_oaf_id);

		Object createObject (in string oaf_id, in StringList params)
			raises (CannotActivate);

	};
};

#if !defined(__BONOBO_GENERIC_FACTORY_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif

#endif
