/*
 * bonobo-factory.idl: Basic object factory interface, based on CORBA
 * LifeCycle version
 */

#ifndef __BONOBO_FACTORY_IDL__
#define __BONOBO_FACTORY_IDL__

module Bonobo {
	typedef sequence<string> stringlist;

	interface GenericFactory {
		exception CannotActivate { };
		/* 'supports' is reserved */
		boolean manufactures (in string obj_goad_id); 

		Object create_object (in string goad_id, in stringlist params)
			raises (CannotActivate);
	};
};

#endif /* ! __BONOBO_FACTORY_IDL__ */
