/*
 * The Bonobo Document Model
 *
 * Author: 
 *     Miguel de Icaza (miguel@gnu.org)
 *
 */
#include <gnome-factory.idl>
#include <gnome-unknown.idl>

#include "gnome-storage.idl"
#include "gnome-persist.idl"

#include "gnome-moniker.idl"

#include "gnome-advise.idl"

#include "gnome-container.idl"
#include "gnome-client-site.idl"
#include "gnome-embeddable.idl"
#include "gnome-inplace.idl"

#include "gnome-progressive.idl"

