/*
 * Bonobo remote printing support
 *
 * Author:
 *    Michael Meeks (michael@helixcode.com)
 *
 * Copyright (C) 2000 Helix Code, Inc.
 */

module Bonobo {

/*
 * The C API needs a user_data pointer.
 */
	typedef sequence<char> PrintData;

	struct PrintContext {
		/*
		 * FIXME: banding / scissoring ? done at client / server end ?
		 */
		double x, y, width, height;
	};

	interface Print : Bonobo::Unknown {
		PrintData render (in PrintContext pc);
	};
};
