module GNOME {

	interface Container : Unknown {
		typedef sequence<Unknown> ObjectList;

		/**
		 * enum_objects:
		 *
		 * Returns: a list of the objects contained by this container
		 */
		ObjectList enum_objects ();

		/**
		 * NotFound{}:
		 * 
		 * This exception is raised if the specified name could not
		 * be found
		 */
		exception NotFound {};

		/**
		 * SyntaxError{}:
		 *
		 * This exception is launched if there is a syntax error
		 * during the name parsing
		 */
		exception SyntaxError {};

		/**
		 * get_object:
		 * @item_name: Item name to bind to
		 * @only_if_exists: if TRUE, only bind if this object currently exists
		 * otherwise, it will try to create the server for it.
		 */
		Unknown get_object (in string item_name, in boolean only_if_exists)
			raises (SyntaxError, NotFound);
	};
};
