/*
 * The Bonobo Document Model
 *
 * Author: 
 *     Miguel de Icaza (miguel@gnu.org)
 *
 */
#if !defined(__BONOBO_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs bonobo/bonobo.h
%}
#pragma inhibit push
#endif

#include <gnome-factory.idl>
#include <gnome-unknown.idl>

#include "gnome-storage.idl"
#include "gnome-persist.idl"

#include "gnome-advise.idl"

#include "gnome-container.idl"
#include "gnome-client-site.idl"
#include "gnome-ui-handler.idl"
#include "gnome-embeddable.idl"

#include "gnome-progressive.idl"

#if !defined(__BONOBO_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif
