/*
 * The Bonobo Document Model
 *
 * Author: 
 *     Miguel de Icaza (miguel@gnu.org)
 *
 */
#ifndef _BONOBO_IDL_INCLUDED_
#define _BONOBO_IDL_INCLUDED_

#if !defined(__BONOBO_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs bonobo/bonobo.h
%}
#pragma inhibit push
#endif

#include <gnome-factory.idl>
#include <gnome-unknown.idl>

/* Storage stuff. */
#include <gnome-storage.idl>
#include <gnome-persist.idl>
#include <gnome-progressive.idl>

#include <gnome-advise.idl>

/* Control stuff. */
#include <gnome-property.idl>
#include <gnome-control.idl>

/* Subdocument stuff. */
#include <gnome-ui-handler.idl>
#include <gnome-container.idl>
#include <gnome-client-site.idl>
#include <gnome-canvas.idl>
#include <gnome-embeddable.idl>

/* Misc. Stuff. */
#include <gnome-desktop.idl>

#if !defined(__BONOBO_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif

#endif /* _BONOBO_IDL_INCLUDED_ */
