/**
 * Sizeable interface
 *
 *   This interface is for controls that can adapt to any
 * size such as an image control, to allow default sizing
 * and 'fit to window' behavior.
 *
 * Author:
 *   Michael Meeks <michael@helixcode.com>
 */

module Bonobo {
	interface Sizeable : Bonobo::Unknown {
		/**
		 * This returns some measure of the default size that the
		 * component would like to be.
		 */
		void get_default_size (out long width, out long height);

		/**
		 * This allows a control contained within a scrolled
		 * window to be told the real viewable dimensions of that
		 * scrolled window to allow it to 'fit to window' etc.
		 */
		void set_window_size  (in  long width, in  long height);
	};
};
