module Bonobo {
	interface UIComponent : Bonobo::Unknown {
		struct Verb {
			string    cname;
			string     label;
			string     descr;
		};
		typedef sequence<Verb> VerbList;

		enum EventType {
			ACTIVATED,
			REMOVED,
			OVERRIDDEN,
			REINSTATED,
			STATE_CHANGED
		};

		VerbList    get_verb_list ();
		oneway void exec_verb     (in string   cname);

		oneway void ui_event     (in string    path,
					  in EventType type,
					  in string    state);
	};

	interface UIContainer : Bonobo::Unknown {
		exception MalFormedXML {};

		void    node_set    (in string path, in string xml,
				     in Bonobo::UIComponent listener)
			raises (MalFormedXML);

		string  node_get    (in string path,
				     in boolean nodeOnly);
		void    node_remove (in string path,
				     in Bonobo::UIComponent by_listener);
		boolean node_exists (in string path);

		/*
		 *  Currently the object should be a Bonobo::Control interface
		 * but this should be probably be changed to a Moniker interface
		 * in due course.
		 */
		void            object_set (in string path,
					     in Bonobo::Unknown control);
		Bonobo::Unknown object_get (in string path);
	};
};
