/*
 * The GNOME::UIHandler Interface
 *
 * The UIHandler interface provides a CORBA service for
 * managing menus and toolbars.  It allows both the top-
 * level container and embedded BonoboObjects to
 * manipulate the application's menu and toolbar items.
 *
 * Author:
 *    Nat Friedman (nat@gnome-support.com)
 *
 */


module GNOME {

       	interface UIHandler : GNOME::Unknown {
		typedef sequence<octet> iobuf;
       
       		enum MenuType {
			MenuTypeBlah
       		};
       
       		enum ToolbarType {
			ToolbarTypeBlah
       		};
       
       		enum PixmapType {
			PixmapTypeBlah
       		};
       
       		enum ModifierType {
			ModifierTypeBlah
       		};
       
       		/*
       		 * Containee ==> Container
       		 */
       
       		/**
		 * register_containee:
		 * @uih: The UIHandler CORBA interface of the
		 * containee which is being registered.
		 *
       		 * This method is used by an embedded component to register
       		 * its GnomeUIHandler with the container's GnomeUIHandler.
		 */
       		void register_containee (in UIHandler uih);
       
       		/**
		 * unregister_containee:
		 * @uih: The UIHandler of the containee which is being
		 * unregistered
		 *
       		 * This method is used by an embedded component to unregister
       		 * its GnomeUIHandler with the container's GnomeUIHandler.
       		 * The container will then
		 */
       		void unregister_containee (in UIHandler uih);
       
       
       		/*
       		 *
		 * Menu.
		 *
		 * These routines are for the creation and
		 * manipulation of menu items.
       		 *
		 */
       		boolean menu_item_create (in string path, in MenuType type, in string label,
       					       in PixmapType pixmap_type, in iobuf pixmap_data,
       					       in long accelerator_key, in ModifierType modifier,
					       in long pos);
       		boolean menu_item_remove (in string path);
       		boolean menu_item_fetch (in string path, out MenuType type, out string label,
       					 out PixmapType pixmap_type, out iobuf pixmap_data,
       					 out unsigned long accelerator_key, out ModifierType modifier,
					 out long pos);
       
       		long menu_item_get_pos (in string path);
       
       		void menu_item_set_sensitivity (in string path, in boolean sensitivity);
       		boolean menu_item_get_sensitivity ();
       
       		void menu_item_set_hidden (in string path, in boolean hidden);
       		boolean menu_item_get_hidden (in string path);
       
       		void menu_item_set_label (in string path, in string label);
       		string menu_item_get_label (in string path);

       		void menu_item_set_hint (in string path, in string hint);
       		string menu_item_get_hint (in string path);
       
       		void menu_item_set_pixmap (in string path, in PixmapType type, in iobuf data);
       		void menu_item_get_pixmap (in string path, out PixmapType type, out iobuf data);
       
       		void menu_item_set_accel (in string path, in unsigned long accelerator_key, in ModifierType ac_mods);
       		void menu_item_get_accel (in string path, out unsigned long accelerator_key, out ModifierType ac_mods);
       
       		void menu_item_toggle_set_state (in string path, in boolean state);
       		boolean menu_item_toggle_get_state (in string path);
       
       		void menu_item_radio_set_state (in string path, in boolean state);
       		boolean menu_item_radio_get_state (in string path);

       		/*
       		 * These methods are for the creation and manipulation of
       		 * dynamic menu items.
       		 *
       		 * FIXME This needs to be rethought.
       		 *
       		 */
       		void menu_item_dynlist_set_maxsize (in string path, in long maxsize);
       		long menu_item_dynlist_get_maxsize (in string path);
       
       		string menu_item_dynlist_generate_new_path (in string dynlist_path);
       
       		void menu_item_dynlist_append_item (in string dynlist_path, in string item_path);
       		void menu_item_dynlist_prepend_item (in string dynlist_path, in string item_path);
       
       		/*
       		 *
		 * Toolbars.
		 *
		 * These routines are for the creation and
		 * manipulation of toolbar items.
       		 *
		 */
       		boolean toolbar_item_create_full (in string path, in ToolbarType type, in string label,
       					       in PixmapType pixmap_type, in iobuf pixmap_data,
       					       in unsigned long accelerator_key, in ModifierType modifier,
       					       in long pos);
       		boolean toolbar_item_remove (in string path);
       		boolean toolbar_item_fetch (in string path, out ToolbarType type, out string label,
       					 out PixmapType pixmap_type, out iobuf pixmap_data,
       					 out unsigned long accelerator_key, out ModifierType modifier,
       					 out long pos);
       
       		long toolbar_item_get_pos (in string path);
       
       		void toolbar_item_set_sensitivity (in string path, in boolean sensitivity);
       		boolean toolbar_item_get_sensitivity ();
       
       		void toolbar_item_set_hidden (in string path, in boolean hidden);
       		boolean toolbar_item_get_hidden (in string path);
       
       		void toolbar_item_set_label (in string path, in string label);
       		string toolbar_item_get_label (in string path);
       
       		void toolbar_item_set_pixmap (in string path, in PixmapType type, in iobuf data);
       		void toolbar_item_get_pixmap (in string path, out PixmapType type, out iobuf data);
       
       		void toolbar_item_set_accel (in string path, in unsigned long accelerator_key, in ModifierType ac_mods);
       		void toolbar_item_get_accel (in string path, out unsigned long accelerator_key, out ModifierType ac_mods);
       
       		void toolbar_item_toggle_set_state (in string path, in boolean state);
       		boolean toolbar_item_toggle_get_state (in string path);
       
       		void toolbar_item_radio_set_state (in string path, in boolean state);
       		boolean toolbar_item_radio_get_state (in string path);
       
       		/*
       		 * These methods allow embedded components to create UI groups
       		 * and manipulate them.
       		 */
       		long group_create ();
       		void group_destroy (in long gid);

		typedef sequence<string> StringSeq;

       		void group_add_menu_items (in long gid, in StringSeq paths);
       		void group_add_toolbar_items (in long gid, in StringSeq paths);
       
       		void group_get_members (in long gid, out StringSeq paths);
       
       		void group_set_sensitivity (in long gid, in boolean sensitivity);
       		void group_set_hidden (in long gid, in boolean sensitivity);
       
       		/*
       		 * Container ==> Containee
       		 */
       
       		/*
       		 * These methods are used by containers to notify containees
       		 * that a menu or toolbar item has been activated or
       		 * overriden.
       		 */
       
       		void item_activated (in string path);
       		void item_overriden (in string path);
       
       	};
       
} ;

